trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/FinanceApp2.Api.csproj'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/FinanceApp2.Api.csproj'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Install EF Tool
  inputs:
    command: custom
    custom: tool
    arguments: install --global dotnet-ef
- script: echo "##vso[task.prependpath]$(USERPROFILE)\.dotnet\tools"
  displayName: Add dotnet tools to PATH
- task: DotNetCoreCLI@2
  displayName: Create EF Migration Bundle for LoggingDbContext
  inputs:
    command: custom
    custom: ef
    workingDirectory: '$(Build.SourcesDirectory)'
    arguments: >
      migrations bundle
      --context LoggingDbContext
      --project FinanceApp2.Api/FinanceApp2.Api.csproj
      --startup-project FinanceApp2.Api/FinanceApp2.Api.csproj
      --configuration $(buildConfiguration)
      --output $(Build.ArtifactStagingDirectory)/efbundle_logging.exe
- task: DotNetCoreCLI@2
  displayName: Create EF Migration Bundle for AppDbContext
  inputs:
    command: custom
    custom: ef
    workingDirectory: '$(Build.SourcesDirectory)'
    arguments: >
      migrations bundle
      --context AppDbContext
      --project FinanceApp2.Api/FinanceApp2.Api.csproj
      --startup-project FinanceApp2.Api/FinanceApp2.Api.csproj
      --configuration $(buildConfiguration)
      --output $(Build.ArtifactStagingDirectory)/efbundle_app.exe
- task: DotNetCoreCLI@2
  displayName: Create EF Migration Bundle for AuthDbContext
  inputs:
    command: custom
    custom: ef
    workingDirectory: '$(Build.SourcesDirectory)'
    arguments: >
      migrations bundle
      --context AuthDbContext
      --project FinanceApp2.Api/FinanceApp2.Api.csproj
      --startup-project FinanceApp2.Api/FinanceApp2.Api.csproj
      --configuration $(buildConfiguration)
      --output $(Build.ArtifactStagingDirectory)/efbundle_auth.exe
- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: False
    projects: '**/FinanceApp2.Api.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/api'
    zipAfterPublish: True
- task: PublishPipelineArtifact@1
  displayName: Upload
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'FinanceApp2Api_artifact'