trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/FinanceApp2.Api.csproj'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: False
    projects: '**/FinanceApp2.Api.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/api'
    zipAfterPublish: True
- task: PublishPipelineArtifact@1
  displayName: Upload
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/api'
    artifactName: 'FinanceApp2.Api artifact'