export const ApiErrorCodes = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_REQUEST_PARAMETERS: 'INVALID_REQUEST_PARAMETERS',
  TOKEN_INVALID_OR_EXPIRED: 'TOKEN_INVALID_OR_EXPIRED',
  PASSWORD_DOES_NOT_MEET_REQUIREMENTS: 'PASSWORD_DOES_NOT_MEET_REQUIREMENTS',
  EMAIL_ADDRESS_ALREADY_IN_USE: 'EMAIL_ADDRESS_ALREADY_IN_USE',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  AUTH_NO_LONGER_VALID: 'AUTH_NO_LONGER_VALID',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  TOOMANYREQUESTS: 'TOOMANYREQUESTS',
} as const;
